<?php

namespace Serge\GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KasJcommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KasJcommentsRepository extends EntityRepository
{
}