guestbook_homepage:
    pattern:  /
    defaults: { _controller: GuestbookBundle:Default:index }

guestbook_view:
    pattern:  /view/{id}
    defaults: { _controller: GuestbookBundle:Default:view }

guestbook_delete:
    pattern:  /delete/{id}
    defaults: { _controller: GuestbookBundle:Default:delete } 